<a href="https://colab.research.google.com/github/sk-shahsi/ML_Model/blob/master/Cap_Stone_Project01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
from google.colab import drive

In [8]:
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [4]:
netflix_dataset = pd.read_csv('/content/drive/MyDrive/Cap_Stone_Project_01/combined_data_1.txt.zip',header=None,names=["CustId","Rating"],usecols=[0,1])

In [5]:
netflix_dataset

           CustId  Rating
0              1:     NaN
1         1488844     3.0
2          822109     5.0
3          885013     4.0
4           30878     4.0
...           ...     ...
24058258  2591364     2.0
24058259  1791000     2.0
24058260   512536     5.0
24058261   988963     3.0
24058262  1704416     3.0

[24058263 rows x 2 columns]

In [9]:
#if ratingis none => value of custId=> Moveid

In [10]:

# netflix_dataset['CustID'].nunique()
#Movie count
#CustomerCount

In [11]:
movie_count = netflix_dataset.isnull().sum().sum()
movie_count

4499

In [12]:
cust_count = netflix_dataset['CustId'].nunique()
cust_count = cust_count-movie_count
cust_count

470758

In [13]:
# how many people have rated movie as 1,2,3,4,5

In [14]:
rating_count = netflix_dataset.groupby('Rating')["Rating"].agg(['count'])

In [15]:
rating_count

          count
Rating
1.0     1118186
2.0     2439073
3.0     6904181
4.0     8085741
5.0     5506583

In [16]:
netflix_dataset["Rating"].value_counts()

Rating
4.0    8085741
3.0    6904181
5.0    5506583
2.0    2439073
1.0    1118186
Name: count, dtype: int64

In [17]:
movie_id=None
movie_np=[]
for cust_id in netflix_dataset['CustId']:
  if':' in cust_id:
    movie_id = int(cust_id.replace(":",""))
  movie_np.append(movie_id)

In [18]:
movie_np

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 ...]

In [19]:
netflix_dataset["movieId"] = movie_np

In [20]:
netflix_dataset

           CustId  Rating  movieId
0              1:     NaN        1
1         1488844     3.0        1
2          822109     5.0        1
3          885013     4.0        1
4           30878     4.0        1
...           ...     ...      ...
24058258  2591364     2.0     4499
24058259  1791000     2.0     4499
24058260   512536     5.0     4499
24058261   988963     3.0     4499
24058262  1704416     3.0     4499

[24058263 rows x 3 columns]

In [21]:
netflix_dataset.dropna(inplace=True)

In [22]:
netflix_dataset

           CustId  Rating  movieId
1         1488844     3.0        1
2          822109     5.0        1
3          885013     4.0        1
4           30878     4.0        1
5          823519     3.0        1
...           ...     ...      ...
24058258  2591364     2.0     4499
24058259  1791000     2.0     4499
24058260   512536     5.0     4499
24058261   988963     3.0     4499
24058262  1704416     3.0     4499

[24053764 rows x 3 columns]

In [23]:
netflix_dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 24053764 entries, 1 to 24058262
Data columns (total 3 columns):
 #   Column   Dtype
---  ------   -----
 0   CustId   object
 1   Rating   float64
 2   movieId  int64
dtypes: float64(1), int64(1), object(1)
memory usage: 734.1+ MB

In [24]:
netflix_dataset['CustId']=netflix_dataset['CustId'].astype(int)

In [25]:
netflix_dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 24053764 entries, 1 to 24058262
Data columns (total 3 columns):
 #   Column   Dtype
---  ------   -----
 0   CustId   int64
 1   Rating   float64
 2   movieId  int64
dtypes: float64(1), int64(2)
memory usage: 734.1 MB

In [26]:
#pre fltring
#now we will remove the users has less movie rated
#we will remove the movie that has been rate less in number

In [27]:
# dataframe of movie_summary have all movie id and its counts

In [28]:
movie_summary = netflix_dataset.groupby("movieId")["Rating"].agg(['count'])

In [29]:
movie_summary

         count
movieId
1          547
2          145
3         2012
4          142
5         1140
...        ...
4495       614
4496      9519
4497       714
4498       269
4499       428

[4499 rows x 1 columns]

In [30]:
# we will set up benchMark =>60 percentile

In [31]:
movie_benchmark = round(movie_summary['count'].quantile(0.6),0)

In [32]:
movie_benchmark

908.0

In [33]:
#

In [34]:
drop_movie_list = movie_summary[movie_summary['count']<movie_benchmark].index

In [35]:
drop_movie_list

Index([   1,    2,    4,    7,    9,   10,   11,   12,   13,   14,
       ...
       4480, 4481, 4486, 4487, 4491, 4494, 4495, 4497, 4498, 4499],
      dtype='int64', name='movieId', length=2699)

In [36]:
len(drop_movie_list)

2699

In [37]:
#

In [38]:
cust_summary = netflix_dataset.groupby("CustId")["Rating"].agg(["count"])

In [39]:
cust_summary

         count
CustId
6          153
7          195
8           21
10          49
25           4
...        ...
2649404     12
2649409     10
2649421      3
2649426     74
2649429     62

[470758 rows x 1 columns]

In [40]:
cust_benchmark = round(cust_summary['count'].quantile(0.6),0)
cust_benchmark

36.0

In [41]:
drop_cust_list = cust_summary[cust_summary['count']<cust_benchmark].index

In [42]:
drop_cust_list

Index([      8,      25,      33,      83,      94,     126,     130,     133,
           142,     149,
       ...
       2649337, 2649343, 2649351, 2649376, 2649379, 2649384, 2649401, 2649404,
       2649409, 2649421],
      dtype='int64', name='CustId', length=282042)

In [43]:
len(drop_cust_list)

282042

In [44]:
print("The shape of data before triming:",netflix_dataset.shape)
netflix_dataset = netflix_dataset[~netflix_dataset['movieId'].isin(drop_movie_list)]
netflix_dataset = netflix_dataset[~netflix_dataset['CustId'].isin(drop_cust_list)]
print("The shape of data after triming:",netflix_dataset.shape)

The shape of data before triming: (24053764, 3)
The shape of data after triming: (19695836, 3)

In [45]:
#Model Bulding

In [46]:
df_titles = pd.read_csv("/content/drive/MyDrive/Cap_Stone_Project_01/Copy of movie_titles.csv",encoding="ISO-8859-1",header=None,usecols=[0,1,2],names=["MovieID","Date","Movie Name"])

In [47]:
df_titles

       MovieID    Date                                         Movie Name
0            1  2003.0                                    Dinosaur Planet
1            2  2004.0                         Isle of Man TT 2004 Review
2            3  1997.0                                          Character
3            4  1994.0                       Paula Abdul's Get Up & Dance
4            5  2004.0                           The Rise and Fall of ECW
...        ...     ...                                                ...
17765    17766  2002.0  Where the Wild Things Are and Other Maurice Se...
17766    17767  2004.0                  Fidel Castro: American Experience
17767    17768  2000.0                                              Epoch
17768    17769  2003.0                                        The Company
17769    17770  2003.0                                       Alien Hunter

[17770 rows x 3 columns]

In [48]:
# surpise
# it is a libearary in python use for building recomendation

In [49]:
!pip install numpy==1.26.4

Requirement already satisfied: numpy==1.26.4 in /usr/local/lib/python3.12/dist-packages (1.26.4)

In [51]:
!pip install scikit-surprise==1.1.4

Collecting scikit-surprise==1.1.4
  Downloading scikit_surprise-1.1.4.tar.gz (154 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 154.4/154.4 kB 4.4 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-surprise==1.1.4) (1.5.3)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.12/dist-packages (from scikit-surprise==1.1.4) (1.26.4)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-surprise==1.1.4) (1.16.3)
Building wheels for collected packages: scikit-surprise
  Building wheel for scikit-surprise (pyproject.toml) ... done
  Created wheel for scikit-surprise: filename=scikit_surprise-1.1.4-cp312-cp312-linux_x86_64.whl size=2581306 sha256=6e8d38f5fd15356736204be16e4f9de235c259c970698014192e48fa8ac7a87f
  Stored in directory: /root/.cache/pip/wheels/75/fa/bc/739bc2cb1fbaab6061854e6cfbb81a0ae52c92a502a7fa454b
Successfully built scikit-surprise
Installing collected packages: scikit-surprise
Successfully installed scikit-surprise-1.1.4

In [52]:
import surprise
print(surprise.__version__)

1.1.4

In [53]:
from surprise import Reader,SVD,Dataset

In [54]:
model = SVD()

In [55]:
reader=Reader()

In [57]:
data = Dataset.load_from_df(netflix_dataset[['CustId','movieId',"Rating"]][:100000],reader)

In [58]:
type(data)

surprise.dataset.DatasetAutoFolds

In [59]:
from surprise.model_selection import cross_validate

In [60]:
cross_validate(model,data,measures=['RMSE'],cv=3)

{'test_rmse': array([1.02509434, 1.01916526, 1.01341415]),
 'fit_time': (1.9532256126403809, 1.5618393421173096, 1.2862696647644043),
 'test_time': (0.6065125465393066, 0.4002525806427002, 0.15133070945739746)}

In [61]:
from surprise.model_selection import cross_validate

In [62]:
cross_validate(model,data,measures=['RMSE'],cv=3)

{'test_rmse': array([1.01439213, 1.02062508, 1.02130857]),
 'fit_time': (1.773425579071045, 2.005131721496582, 1.3461742401123047),
 'test_time': (0.2810404300689697, 0.22397851943969727, 0.15043902397155762)}

In [ ]:
#Recomendation

In [63]:
netflix_dataset

           CustId  Rating  movieId
696        712664     5.0        3
697       1331154     4.0        3
698       2632461     3.0        3
699         44937     5.0        3
700        656399     4.0        3
...           ...     ...      ...
24056842  1055714     5.0     4496
24056843  2643029     4.0     4496
24056844   267802     4.0     4496
24056845  1559566     3.0     4496
24056846   293198     3.0     4496

[19695836 rows x 3 columns]

In [64]:
df_titles

       MovieID    Date                                         Movie Name
0            1  2003.0                                    Dinosaur Planet
1            2  2004.0                         Isle of Man TT 2004 Review
2            3  1997.0                                          Character
3            4  1994.0                       Paula Abdul's Get Up & Dance
4            5  2004.0                           The Rise and Fall of ECW
...        ...     ...                                                ...
17765    17766  2002.0  Where the Wild Things Are and Other Maurice Se...
17766    17767  2004.0                  Fidel Castro: American Experience
17767    17768  2000.0                                              Epoch
17768    17769  2003.0                                        The Company
17769    17770  2003.0                                       Alien Hunter

[17770 rows x 3 columns]

In [65]:
user_rating = netflix_dataset[netflix_dataset['CustId']==1331154]

In [66]:
user_rating

           CustId  Rating  movieId
697       1331154     4.0        3
5178      1331154     4.0        8
31460     1331154     3.0       18
92840     1331154     4.0       30
224761    1331154     3.0       44
...           ...     ...      ...
23439584  1331154     4.0     4389
23546489  1331154     2.0     4402
23649431  1331154     4.0     4432
23844441  1331154     3.0     4472
23985561  1331154     4.0     4488

[253 rows x 3 columns]

In [67]:
user_1331154 = df_titles.copy()

In [68]:
user_1331154

       MovieID    Date                                         Movie Name
0            1  2003.0                                    Dinosaur Planet
1            2  2004.0                         Isle of Man TT 2004 Review
2            3  1997.0                                          Character
3            4  1994.0                       Paula Abdul's Get Up & Dance
4            5  2004.0                           The Rise and Fall of ECW
...        ...     ...                                                ...
17765    17766  2002.0  Where the Wild Things Are and Other Maurice Se...
17766    17767  2004.0                  Fidel Castro: American Experience
17767    17768  2000.0                                              Epoch
17768    17769  2003.0                                        The Company
17769    17770  2003.0                                       Alien Hunter

[17770 rows x 3 columns]

In [70]:
user_1331154['Estimate_Score'] = user_1331154['MovieID'].apply(lambda x: model.predict(1331154,x).est)

In [71]:
user_1331154

,MovieID,Date,Movie Name,Estimate_Score
0,1,2003.0,Dinosaur Planet,3.587025
1,2,2004.0,Isle of Man TT 2004 Review,3.587025
2,3,1997.0,Character,3.666840
3,4,1994.0,Paula Abdul's Get Up & Dance,3.587025
4,5,2004.0,The Rise and Fall of ECW,3.608697
...,...,...,...,...
17765,17766,2002.0,Where the Wild Things Are and Other Maurice Se...,3.587025
17766,17767,2004.0,Fidel Castro: American Experience,3.587025
17767,17768,2000.0,Epoch,3.587025
17768,17769,2003.0,The Company,3.587025
17769,17770,2003.0,Alien Hunter,3.587025

In [72]:
user_1331154.sort_values(by='Estimate_Score',ascending=False)

,MovieID,Date,Movie Name,Estimate_Score
24,25,1997.0,Inspector Morse 31: Death Is Now My Neighbour,4.146562
27,28,2002.0,Lilo and Stitch,3.866370
2,3,1997.0,Character,3.666840
4,5,2004.0,The Rise and Fall of ECW,3.608697
0,1,2003.0,Dinosaur Planet,3.587025
...,...,...,...,...
7,8,2004.0,What the #$*! Do We Know!?,3.165150
5,6,1997.0,Sick,3.098140
16,17,2005.0,7 Seconds,2.834057
23,24,1981.0,My Bloody Valentine,2.818244
25,26,2004.0,Never Die Alone,2.511324

In [73]:
user_1331154.head(10)

   MovieID    Date                    Movie Name  Estimate_Score
0        1  2003.0               Dinosaur Planet        3.587025
1        2  2004.0    Isle of Man TT 2004 Review        3.587025
2        3  1997.0                     Character        3.666840
3        4  1994.0  Paula Abdul's Get Up & Dance        3.587025
4        5  2004.0      The Rise and Fall of ECW        3.608697
5        6  1997.0                          Sick        3.098140
6        7  1992.0                         8 Man        3.587025
7        8  2004.0    What the #$*! Do We Know!?        3.165150
8        9  1991.0      Class of Nuke 'Em High 2        3.587025
9       10  2001.0                       Fighter        3.587025