<a href="https://colab.research.google.com/github/sk-shahsi/ML_Model/blob/master/Gradint_decent_26_08_2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Find w, b that minimize the loss

#### Gradient Desent -> Gradient descent is an iterative optimization algorithm used to find the minimum of a function. In machine learning, it minimizes error (loss) by adjusting model parameters (like weights and biases) step-by-step in the direction of the steepest decrease.

In [2]:
# 1. Calculate the slope
# 2. Determine which direction goes downhill
# 3. Take small step (learning rate)
# 4. Calculate the Slope again
# 5. Repeat

In [3]:
# change in loss with respect to change in weight

In [4]:
# d loss / d w

In [5]:
# If gradint comes as positive you need to decrease the weight / bias
# If gradint comes as negative you need to increase the weight / bias

In [6]:
# Types of GD ->

In [7]:
# 1. Batch Gradient Descent ->
# Uses all the training data to calculate one gradient
# Uses when you have small datasets

# 1 Update = Entire Dataset

In [8]:
# 2. Stochastic Gradient Descent ->
# Use one sample at a time
# Sample 1 -> Update
# Sample 2 -> Update
# Sample 3 -> Update
# ...

# 1 Update = 1 Sample
# It is noisy because every individual sample can give a slightly different gradient

In [9]:
# 3. Mini Batch Gradient Descent ->
# Uses a small group of samples

# 1000 Samples

# 32 Samples -> Update
# 32 Samples -> Update
# 32 Samples -> Update
# ...

# 1 Update = Small Batch

# This is the most commonly used approach in Deep Learning

In [10]:
# Dataset Link -> https://drive.google.com/file/d/1INrQV6UcxSU2E1N33EwPSEui7iUptqvL/view?usp=sharing

In [11]:
import pandas as pd

In [12]:
df = pd.read_csv("/content/Salary Data.csv")

In [13]:
df

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0
1,28.0,Female,Master's,Data Analyst,3.0,65000.0
2,45.0,Male,PhD,Senior Manager,15.0,150000.0
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0
4,52.0,Male,Master's,Director,20.0,200000.0
...,...,...,...,...,...,...
370,35.0,Female,Bachelor's,Senior Marketing Analyst,8.0,85000.0
371,43.0,Male,Master's,Director of Operations,19.0,170000.0
372,29.0,Female,Bachelor's,Junior Project Manager,2.0,40000.0
373,34.0,Male,Bachelor's,Senior Operations Coordinator,7.0,90000.0
374,44.0,Female,PhD,Senior Business Analyst,15.0,150000.0

In [14]:
# EDA & Data Preprocessing ->
# Null
# Duplicates
# Outliers
# Label Encoding

# time -> 8:20

In [15]:
df.isnull().sum()

Age                    2
Gender                 2
Education Level        2
Job Title              2
Years of Experience    2
Salary                 2
dtype: int64

In [16]:
df.dropna(how="all", inplace=True)      # how -> any / all

In [17]:
df.isnull().sum()

Age                    0
Gender                 0
Education Level        0
Job Title              0
Years of Experience    0
Salary                 0
dtype: int64

In [18]:
# Duplicates ->
df.duplicated().sum()

np.int64(49)

In [19]:
df.shape

(373, 6)

In [20]:
df.drop_duplicates(inplace=True)

In [21]:
from sklearn.preprocessing import LabelEncoder

In [22]:
le = LabelEncoder()
for i in df.columns:
  if(df[i].dtype == "object"):
    df[i] = le.fit_transform(df[i])

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 324 entries, 0 to 371
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Age                  324 non-null    float64
 1   Gender               324 non-null    int64
 2   Education Level      324 non-null    int64
 3   Job Title            324 non-null    int64
 4   Years of Experience  324 non-null    float64
 5   Salary               324 non-null    float64
dtypes: float64(3), int64(3)
memory usage: 17.7 KB

In [24]:
X = df.drop(columns="Salary")
y = df["Salary"]

In [25]:
X.shape

(324, 5)

In [26]:
y.shape

(324,)

In [27]:
# VIF / RFE
# PCA / LDA

In [28]:
from sklearn.feature_selection import SelectKBest, f_regression

In [29]:
model_x_f = SelectKBest(f_regression, k=2)
model_x_f.fit(X, y)

SelectKBest(k=2, score_func=<function f_regression at 0x7e07bd8616c0>)

In [30]:
model_x_f.get_support()

array([ True, False, False, False,  True])

In [31]:
X.columns

Index(['Age', 'Gender', 'Education Level', 'Job Title', 'Years of Experience'], dtype='object')

In [32]:
# Which value comes as True that only we need to take

In [33]:
X = df.drop(columns = ['Gender', 'Education Level', 'Job Title', "Salary"])
y = df["Salary"]

In [34]:
X.shape

(324, 2)

In [35]:
X.columns

Index(['Age', 'Years of Experience'], dtype='object')

In [36]:
import numpy as np
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [37]:
X

array([[-0.75023085, -0.76182086],
       [-1.30774185, -1.06301666],
       [ 1.06167989,  0.74415815],
       [-0.19271985, -0.46062506],
       [ 2.03732414,  1.49714765],
       [-1.1683641 , -1.21361456],
       [ 0.64354665,  0.29236444],
       [-0.8896086 , -0.91241876],
       [-1.58649735, -1.36421246],
       [ 0.08603565, -0.00883136],
       [-1.1683641 , -1.06301666],
       [ 1.47981314,  1.19595185],
       [-0.3320976 , -0.61122296],
       [ 0.36479115,  0.59356024],
       [-1.4471196 , -1.21361456],
       [ 0.92230215,  0.89475605],
       [-0.6108531 , -0.46062506],
       [ 0.2254134 ,  0.29236444],
       [-1.7258751 , -1.51481037],
       [ 1.89794639,  1.79834345],
       [-0.47147535, -0.76182086],
       [ 1.34043539,  1.34654975],
       [-1.02898635, -1.21361456],
       [-0.19271985, -0.15942926],
       [ 0.5041689 ,  0.44296234],
       [-1.30774185, -1.06301666],
       [-0.0533421 ,  0.14176654],
       [-1.86525285, -1.36421246],
       [ 0.7829244 ,  0.74415815],
       [-0.6108531 , -0.61122296],
       [ 1.75856864,  2.25013715],
       [-0.8896086 , -0.91241876],
       [-1.1683641 , -1.06301666],
       [ 0.2254134 , -0.00883136],
       [ 1.20105764,  1.49714765],
       [-1.4471196 , -1.21361456],
       [-0.3320976 , -0.46062506],
       [ 0.64354665,  0.59356024],
       [-1.58649735, -1.36421246],
       [ 1.61919089,  1.64774555],
       [-0.47147535, -0.76182086],
       [ 1.47981314,  1.19595185],
       [-1.02898635, -1.06301666],
       [-0.19271985, -0.31002716],
       [ 0.5041689 ,  0.44296234],
       [-1.30774185, -1.21361456],
       [-0.75023085, -0.76182086],
       [ 1.06167989,  0.89475605],
       [ 0.08603565,  0.14176654],
       [-1.7258751 , -1.51481037],
       [ 1.89794639,  1.79834345],
       [-0.6108531 , -0.46062506],
       [ 0.36479115,  0.29236444],
       [ 1.34043539,  1.34654975],
       [-1.1683641 , -1.06301666],
       [-0.19271985, -0.15942926],
       [-1.4471196 , -1.21361456],
       [ 0.7829244 ,  1.04535395],
       [-1.02898635, -0.91241876],
       [-0.3320976 , -0.46062506],
       [ 1.89794639,  1.94894135],
       [-1.1683641 , -1.06301666],
       [ 0.36479115,  0.29236444],
       [ 1.34043539,  1.64774555],
       [-1.58649735, -1.36421246],
       [ 0.08603565, -0.00883136],
       [ 1.20105764,  1.34654975],
       [-0.8896086 , -0.76182086],
       [-0.47147535, -0.31002716],
       [ 1.61919089,  1.19595185],
       [-0.6108531 , -0.61122296],
       [ 0.2254134 ,  0.14176654],
       [ 1.06167989,  0.89475605],
       [-1.30774185, -1.21361456],
       [ 0.64354665,  0.59356024],
       [-0.0533421 , -0.00883136],
       [ 1.75856864,  1.79834345],
       [-0.75023085, -0.61122296],
       [ 1.47981314,  1.49714765],
       [-1.02898635, -1.06301666],
       [-0.19271985, -0.31002716],
       [ 0.5041689 ,  0.44296234],
       [-1.7258751 , -1.51481037],
       [ 2.03732414,  2.09953925],
       [-1.1683641 , -1.21361456],
       [-0.47147535, -0.00883136],
       [-1.4471196 , -1.21361456],
       [ 0.36479115,  0.74415815],
       [ 1.20105764,  1.64774555],
       [-0.8896086 , -0.61122296],
       [-0.19271985,  0.14176654],
       [-1.1683641 , -1.06301666],
       [ 0.7829244 ,  1.19595185],
       [ 2.03732414,  2.25013715],
       [-0.6108531 , -0.46062506],
       [ 0.2254134 ,  0.29236444],
       [ 1.34043539,  1.79834345],
       [-1.58649735, -1.36421246],
       [ 0.08603565, -0.00883136],
       [ 1.06167989,  1.49714765],
       [-0.8896086 , -0.76182086],
       [-0.3320976 , -0.31002716],
       [ 1.61919089,  1.34654975],
       [-0.6108531 , -0.76182086],
       [ 0.2254134 ,  0.44296234],
       [ 0.92230215,  0.89475605],
       [-1.02898635, -1.06301666],
       [-0.19271985, -0.46062506],
       [ 0.5041689 ,  0.59356024],
       [-1.30774185, -1.21361456],
       [ 0.64354665,  0.74415815],
       [-0.0533421 , -0.15942926],
       [ 1.75856864,  1.79834345],
       [-0.75023085, -0.61122296],
       [-2.0046306 , -1.43951142],
       [-0.8896086 , -0.61122296],
       [ 0.36479115,  0.74415815],
       [ 1.47981314,  1.49714765],
       [-1.1683641 , -1.06301666],
       [-0.3320976 , -0.00883136],
       [ 0.64354665,  1.04535395],
       [ 2.17670189,  2.25013715],
       [-0.6108531 , -0.76182086],
       [ 0.08603565,  0.14176654],
       [ 0.92230215,  0.89475605],
       [-1.58649735, -1.21361456],
       [-0.0533421 , -0.15942926],
       [ 1.06167989,  1.19595185],
       [-0.75023085, -0.91241876],
       [-0.47147535, -0.31002716],
       [ 1.75856864,  1.64774555],
       [-1.1683641 , -1.06301666],
       [ 0.36479115,  0.29236444],
       [ 1.34043539,  1.79834345],
       [-1.4471196 , -1.36421246],
       [ 0.2254134 , -0.00883136],
       [ 1.20105764,  1.34654975],
       [-1.02898635, -0.91241876],
       [-0.19271985, -0.46062506],
       [ 0.7829244 ,  0.59356024],
       [-1.30774185, -1.21361456],
       [ 0.5041689 ,  0.44296234],
       [-0.6108531 , -0.76182086],
       [ 1.34043539,  1.49714765],
       [-1.7258751 , -1.28891351],
       [-0.47147535, -0.31002716],
       [ 0.64354665,  0.89475605],
       [-0.8896086 , -0.91241876],
       [ 0.08603565, -0.00883136],
       [ 1.06167989,  1.34654975],
       [-1.1683641 , -1.06301666],
       [-0.19271985,  0.14176654],
       [ 0.7829244 ,  1.19595185],
       [-1.58649735, -1.21361456],
       [-0.0533421 , -0.15942926],
       [ 0.92230215,  0.59356024],
       [-0.75023085, -0.76182086],
       [-0.6108531 , -0.46062506],
       [ 1.89794639,  1.94894135],
       [-1.30774185, -1.21361456],
       [ 0.2254134 ,  0.29236444],
       [ 1.47981314,  1.64774555],
       [-1.02898635, -1.06301666],
       [-0.3320976 , -0.46062506],
       [ 0.5041689 ,  0.44296234],
       [-1.4471196 , -1.28891351],
       [ 0.36479115,  0.59356024],
       [ 1.20105764,  1.19595185],
       [-0.8896086 , -0.91241876],
       [-0.47147535, -0.15942926],
       [ 1.75856864,  1.49714765],
       [-1.1683641 , -1.21361456],
       [ 0.7829244 ,  0.89475605],
       [-1.58649735, -1.28891351],
       [-0.3320976 , -0.46062506],
       [ 0.64354665,  1.19595185],
       [-0.8896086 , -0.91241876],
       [ 0.08603565, -0.00883136],
       [ 1.20105764,  1.49714765],
       [-1.1683641 , -1.21361456],
       [-0.0533421 , -0.15942926],
       [ 0.92230215,  0.74415815],
       [-1.4471196 , -1.21361456],
       [-0.19271985, -0.31002716],
       [ 0.7829244 ,  0.59356024],
       [-0.6108531 , -0.61122296],
       [-0.47147535, -0.15942926],
       [ 1.75856864,  1.79834345],
       [-1.30774185, -1.28891351],
       [ 0.2254134 ,  0.29236444],
       [ 1.34043539,  1.34654975],
       [-1.02898635, -1.06301666],
       [-0.47147535, -0.46062506],
       [ 0.36479115,  0.44296234],
       [ 0.5041689 ,  0.14176654],
       [ 1.06167989,  1.04535395],
       [-0.75023085, -0.76182086],
       [-0.3320976 , -0.15942926],
       [ 1.61919089,  1.64774555],
       [-1.02898635, -1.06301666],
       [ 0.92230215,  0.89475605],
       [-1.4471196 , -1.28891351],
       [-0.19271985, -0.46062506],
       [ 0.5041689 ,  1.04535395],
       [-0.8896086 , -0.91241876],
       [ 0.2254134 , -0.00883136],
       [ 1.34043539,  1.49714765],
       [-1.02898635, -1.21361456],
       [ 0.08603565, -0.15942926],
       [ 1.06167989,  0.74415815],
       [-1.30774185, -1.21361456],
       [-0.3320976 , -0.31002716],
       [ 0.92230215,  0.59356024],
       [-0.47147535, -0.61122296],
       [-0.3320976 , -0.15942926],
       [ 1.75856864,  1.79834345],
       [-1.1683641 , -1.28891351],
       [ 0.36479115,  0.29236444],
       [ 1.47981314,  1.34654975],
       [-0.8896086 , -1.06301666],
       [-0.6108531 , -0.46062506],
       [ 0.64354665,  0.44296234],
       [-1.30774185, -1.21361456],
       [ 0.36479115,  0.14176654],
       [ 1.20105764,  1.19595185],
       [-0.6108531 , -0.76182086],
       [-0.0533421 , -0.15942926],
       [ 1.89794639,  1.64774555],
       [-1.02898635, -1.06301666],
       [ 0.7829244 ,  0.74415815],
       [-1.4471196 , -1.28891351],
       [-0.3320976 , -0.31002716],
       [ 0.64354665,  0.44296234],
       [-0.75023085, -1.06301666],
       [-0.0533421 , -0.15942926],
       [ 1.06167989,  0.89475605],
       [-0.6108531 , -0.76182086],
       [ 0.2254134 , -0.00883136],
       [ 0.92230215,  1.19595185],
       [-1.1683641 , -1.28891351],
       [ 0.08603565, -0.00883136],
       [ 1.20105764,  1.34654975],
       [-0.47147535, -0.61122296],
       [-0.19271985, -0.31002716],
       [ 1.61919089,  1.64774555],
       [-0.8896086 , -1.06301666],
       [ 0.5041689 ,  0.14176654],
       [ 1.34043539,  1.49714765],
       [-1.1683641 , -1.28891351],
       [-0.0533421 , -0.00883136],
       [-0.8896086 , -1.06301666],
       [ 0.64354665,  0.29236444],
       [-1.1683641 , -1.28891351],
       [-0.19271985, -0.31002716],
       [ 0.92230215,  0.74415815],
       [-0.6108531 , -0.91241876],
       [ 0.2254134 , -0.15942926],
       [ 1.06167989,  0.89475605],
       [-0.75023085, -0.91241876],
       [-0.0533421 , -0.31002716],
       [ 1.34043539,  1.49714765],
       [-1.02898635, -1.21361456],
       [ 0.08603565, -0.15942926],
       [ 1.20105764,  1.04535395],
       [-0.47147535, -0.76182086],
       [-0.19271985, -0.31002716],
       [ 1.61919089,  1.64774555],
       [-0.8896086 , -1.06301666],
       [ 1.34043539,  1.34654975],
       [-1.1683641 , -1.28891351],
       [-0.3320976 , -0.15942926],
       [ 0.92230215,  0.74415815],
       [-0.6108531 , -0.91241876],
       [ 0.92230215,  0.44296234],
       [-0.75023085, -0.91241876],
       [ 0.08603565, -0.00883136],
       [ 1.61919089,  1.64774555],
       [-1.1683641 , -1.21361456],
       [-0.3320976 , -0.46062506],
       [ 1.06167989,  0.59356024],
       [-0.6108531 , -0.91241876],
       [ 0.36479115,  0.29236444],
       [ 0.92230215,  0.89475605],
       [-1.02898635, -1.21361456],
       [-0.0533421 , -0.15942926],
       [ 1.47981314,  1.49714765],
       [-0.8896086 , -1.06301666],
       [ 0.08603565, -0.15942926],
       [-0.6108531 , -0.76182086],
       [-0.19271985, -0.31002716],
       [ 0.64354665,  0.29236444],
       [-0.47147535, -0.61122296],
       [-1.02898635, -1.21361456],
       [-0.0533421 , -0.00883136],
       [ 1.06167989,  0.89475605],
       [-0.75023085, -0.91241876],
       [ 0.2254134 ,  0.29236444],
       [ 1.34043539,  1.49714765],
       [-1.1683641 , -1.21361456],
       [-0.19271985, -0.15942926],
       [ 0.7829244 ,  0.74415815],
       [-0.75023085, -1.06301666],
       [ 1.47981314,  1.64774555],
       [-0.8896086 , -1.06301666],
       [ 0.36479115,  0.29236444],
       [ 1.06167989,  0.89475605],
       [-0.6108531 , -0.91241876],
       [-0.19271985, -0.31002716],
       [ 1.34043539,  1.34654975],
       [-1.1683641 , -1.21361456],
       [-0.47147535, -0.46062506],
       [ 0.92230215,  0.74415815],
       [-0.6108531 , -0.76182086],
       [-0.3320976 , -0.31002716],
       [ 0.7829244 ,  1.19595185],
       [-0.8896086 , -1.06301666],
       [ 0.5041689 ,  0.59356024],
       [ 0.92230215,  0.89475605],
       [ 1.06167989,  1.34654975],
       [-1.30774185, -1.36421246],
       [-0.19271985, -0.31002716],
       [ 0.92230215,  0.89475605],
       [-0.8896086 , -1.06301666],
       [ 0.7829244 ,  1.34654975]])

In [38]:
y = np.log10(y)

In [39]:
y

0      4.954243
1      4.812913
2      5.176091
3      4.778151
4      5.301030
         ...
348    4.544068
349    5.041393
350    5.204120
351    4.740363
371    5.230449
Name: Salary, Length: 324, dtype: float64

In [40]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [41]:
y_train.shape

(259,)

In [42]:
from sklearn.linear_model import LinearRegression

In [43]:
model = LinearRegression()

In [44]:
model.fit(X_train, y_train)

LinearRegression()

In [45]:
y_pred = model.predict(X_test)

In [46]:
y_pred

array([5.0834123 , 5.05192298, 4.81688249, 5.0834123 , 4.86298707,
       4.99120315, 5.2431177 , 4.76851911, 5.31619399, 4.91135045,
       4.7392886 , 4.72467334, 5.03504892, 4.62402715, 5.19475432,
       5.03504892, 4.84837181, 5.10254516, 4.84837181, 5.2431177 ,
       5.2431177 , 4.58410081, 4.63246418, 5.27460702, 5.13177568,
       5.15090854, 4.78539317, 5.1655238 , 4.67630996, 5.22398484,
       4.89673519, 4.94058097, 4.67630996, 4.88437874, 4.67630996,
       4.94283977, 5.14639094, 4.69092522, 5.0811535 , 4.86750467,
       4.83149775, 4.58635961, 4.86524587, 5.1677826 , 4.6616947 ,
       4.80226724, 4.87986113, 4.69318402, 5.25547415, 5.10028636,
       4.72241454, 4.69318402, 5.18013906, 5.05418179, 5.13177568,
       5.32071159, 4.77303672, 4.89899399, 4.86750467, 4.87986113,
       4.93048331, 5.35220091, 4.92822451, 4.78539317, 4.64707944])

In [47]:
y_pred = 10**y_pred
y_test = 10**y_test

In [48]:
y_pred

array([121174.79743123, 112699.75802017,  65596.77578583, 121174.79743123,
        72943.57939702,  97994.82641609, 175032.09802333,  58683.91970732,
       207106.62451987,  81536.19673987,  54864.14270736,  53048.5281829 ,
       108404.90249432,  42075.29352568, 156586.5008387 , 108404.90249432,
        70529.66357361, 126632.49532148,  70529.66357361, 175032.09802333,
       175032.09802333,  38379.63192349,  42900.68084382, 188194.53914128,
       135448.96212853, 141549.56663141,  61008.89718559, 146394.17698933,
        47458.05767406, 167488.43942541,  78837.92614335,  87212.94795846,
        47458.05767406,  76626.45518488,  47458.05767406,  87667.73147373,
       140084.77600287,  49082.33532638, 120546.19327539,  73706.31089834,
        67841.86086084,  38579.76761813,  73323.95339229, 147157.56889367,
        45887.53210739,  63425.98712501,  75833.50529373,  49338.28169122,
       180083.5962382 , 125975.5789122 ,  52773.33461143,  49338.28169122,
       151404.59675294, 113287.4458959 , 135448.96212853, 209272.22631731,
        59297.54567072,  79249.0369936 ,  73706.31089834,  75833.50529373,
        85208.5769572 , 225009.53043257,  84766.55050678,  61008.89718559,
        44368.97981304])

In [49]:
from sklearn.metrics import *

In [50]:
print(f"R2 Score: {r2_score(y_test, y_pred)}")
print(f"MSE: {mean_squared_error(y_test, y_pred)}")
print(f"RMSE: {root_mean_squared_error(y_test, y_pred)}")

R2 Score: 0.7892976698762174
MSE: 498150178.7866163
RMSE: 22319.278186953456

In [51]:
# def initialize()

# def predict_y() -> y = wX + B

# def get_cost()

# def update_weight_bias()

# def run_gradient_descent()

In [52]:
import random

In [67]:
def initialized(dim):
  b = random.random()           # bias
  theta = np.random.rand(dim)   # weight
  return b, theta
# y = w1x1 + w2x2 + w3x3 + .... + B

b, theta = initialized(2)
print(b, theta)

0.6929700973695047 [0.11812376 0.44765039]

In [70]:
def predict_Y(b, theta, X):
  return b + np.dot(X, theta)

Y_hat = predict_Y(b, theta, X)      # Prediction

In [56]:
from sklearn.metrics import *

In [71]:
from sklearn.metrics import *
def get_cost(y, Y_hat):
  return mean_squared_error(y, Y_hat)

get_cost(y, Y_hat)

18.169851253201085

In [72]:
def update_theta(x,y,y_hat,b_0, theta_0, learning_rate):
  db = (np.sum(y_hat-y)*2)/len(y)     # d(Loss)/d(B)
  dw = (np.dot((y_hat-y), x)*2)/len(y)    # d(Loss)/d(W)
  b_1 = b_0 - learning_rate*db
  theta_1 = theta_0 - learning_rate*dw
  return b_1, theta_1

b, theta = update_theta(X, y, Y_hat, b, theta, 0.01)

print(b, theta)

0.7778842242790485 [0.11127678 0.44067504]

In [73]:
def run_gradient_descent(X, Y, alpha, num_iterations):
  b, theta = initialized(X.shape[1])
  ite_num = 0
  gd_iterations_df = pd.DataFrame(columns = ["Iteration", "Cost"])
  result_idx = 0
  for i in range(num_iterations):
    Y_hat = predict_Y(b, theta, X)
    this_cost = get_cost(Y, Y_hat)
    prev_b = b
    prev_theta = theta
    b, theta = update_theta(X, Y, Y_hat, prev_b, prev_theta, alpha)
    # Store the iteration and cost
    if(ite_num%10 == 0):
      gd_iterations_df.loc[result_idx] = [ite_num, this_cost]
      result_idx = result_idx+1
    ite_num = ite_num+1
  return gd_iterations_df, b, theta

gd_iteration_df, b, theta = run_gradient_descent(X, y, alpha=0.01, num_iterations=1000)

In [74]:
gd_iteration_df

    Iteration       Cost
0         0.0  23.802250
1        10.0  15.824657
2        20.0  10.539410
3        30.0   7.029065
4        40.0   4.693613
..        ...        ...
95      950.0   0.022296
96      960.0   0.022295
97      970.0   0.022294
98      980.0   0.022293
99      990.0   0.022292

[100 rows x 2 columns]