<a href="https://colab.research.google.com/github/sk-shahsi/ML_Model/blob/master/k_Means_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [159]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib as plt

In [160]:
df = pd.read_csv("/content/Live.csv")

In [161]:
df

,status_id,status_type,status_published,num_reactions,num_comments,num_shares,num_likes,num_loves,num_wows,num_hahas,num_sads,num_angrys,Column1,Column2,Column3,Column4
0,246675545449582_1649696485147474,video,4/22/2018 6:00,529,512,262,432,92,3,1,1,0,NaN,NaN,NaN,NaN
1,246675545449582_1649426988507757,photo,4/21/2018 22:45,150,0,0,150,0,0,0,0,0,NaN,NaN,NaN,NaN
2,246675545449582_1648730588577397,video,4/21/2018 6:17,227,236,57,204,21,1,1,0,0,NaN,NaN,NaN,NaN
3,246675545449582_1648576705259452,photo,4/21/2018 2:29,111,0,0,111,0,0,0,0,0,NaN,NaN,NaN,NaN
4,246675545449582_1645700502213739,photo,4/18/2018 3:22,213,0,0,204,9,0,0,0,0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7045,1050855161656896_1061863470556065,photo,9/24/2016 2:58,89,0,0,89,0,0,0,0,0,NaN,NaN,NaN,NaN
7046,1050855161656896_1061334757275603,photo,9/23/2016 11:19,16,0,0,14,1,0,1,0,0,NaN,NaN,NaN,NaN
7047,1050855161656896_1060126464063099,photo,9/21/2016 23:03,2,0,0,1,1,0,0,0,0,NaN,NaN,NaN,NaN
7048,1050855161656896_1058663487542730,photo,9/20/2016 0:43,351,12,22,349,2,0,0,0,0,NaN,NaN,NaN,NaN
7049,1050855161656896_1050858841656528,photo,9/10/2016 10:30,17,0,0,17,0,0,0,0,0,NaN,NaN,NaN,NaN

In [162]:
df.columns

Index(['status_id', 'status_type', 'status_published', 'num_reactions',
       'num_comments', 'num_shares', 'num_likes', 'num_loves', 'num_wows',
       'num_hahas', 'num_sads', 'num_angrys', 'Column1', 'Column2', 'Column3',
       'Column4'],
      dtype='object')

In [163]:
df.dtypes

status_id            object
status_type          object
status_published     object
num_reactions         int64
num_comments          int64
num_shares            int64
num_likes             int64
num_loves             int64
num_wows              int64
num_hahas             int64
num_sads              int64
num_angrys            int64
Column1             float64
Column2             float64
Column3             float64
Column4             float64
dtype: object

In [164]:
df.duplicated().sum()

np.int64(51)

In [165]:
df.isnull().sum().sum()

np.int64(28200)

In [166]:
7050/28200*100

25.0

In [167]:
df["Column4"].isna().all()

np.True_

In [168]:
print(df["Column3"].dropna().unique())

[]

In [169]:
count = df.isna().any().sum()
print(count)

4

In [170]:
count = df.status_id.any().sum()
print(count)

1

In [171]:
df["status_id"].nunique()

6997

In [172]:
df[(df["status_type"] == "video") & (df["status_type"] == "Live Selling")].shape[0]

0

In [173]:
df[df["status_type"] == "video"].shape[0]

2334

In [174]:
df[
    (df["status_type"] == "photo") &
    (df["status_published"] == "4/19/2018 22:26")
]["num_likes"]

4592    379
Name: num_likes, dtype: int64

In [175]:
df[
    (df["status_type"] == "video") &
    (df["status_published"] == "7/15/2017 10:52")
]["num_shares"]

6977    167
Name: num_shares, dtype: int64

In [176]:
df = df.drop(['status_id','status_published'],axis=1)

In [177]:
df = df.drop(['Column1','Column2','Column3','Column4'],axis=1)

In [178]:
from sklearn.preprocessing import LabelEncoder

In [179]:
le =LabelEncoder()

In [180]:
df['status_type'] = le.fit_transform(df['status_type'])

In [181]:
from sklearn.preprocessing import MinMaxScaler

In [182]:
scaler = MinMaxScaler()
X=scaler.fit_transform(df)

In [183]:
from sklearn.cluster import KMeans

In [184]:
k = KMeans(n_clusters=3, random_state=42)
k.fit(X)

KMeans(n_clusters=3, random_state=42)

In [185]:
df['Cluster'] = k.labels_

In [186]:
print(df.head())

   status_type  num_reactions  num_comments  num_shares  num_likes  num_loves  \
0            3            529           512         262        432         92
1            1            150             0           0        150          0
2            3            227           236          57        204         21
3            1            111             0           0        111          0
4            1            213             0           0        204          9

   num_wows  num_hahas  num_sads  num_angrys  Cluster
0         3          1         1           0        1
1         0          0         0           0        0
2         1          1         0           0        1
3         0          0         0           0        0
4         0          0         0           0        0

In [187]:
centers = k.cluster_centers_
print(centers)

[[3.28639637e-01 1.90861674e-02 6.46777891e-04 5.25190421e-04
  1.86359211e-02 1.84651223e-03 1.92824619e-03 1.11801300e-03
  2.85144405e-03 1.52714799e-03]
 [1.00000000e+00 5.21304107e-02 3.11157453e-02 3.42830272e-02
  4.34008054e-02 5.50620278e-02 8.96378405e-03 1.12499688e-02
  8.26043457e-03 8.34236034e-03]
 [5.64263323e-01 2.29297699e-01 2.10489844e-03 2.55800838e-03
  2.28213832e-01 4.26799884e-03 6.58532735e-03 1.36772957e-03
  4.70219436e-03 5.05612296e-04]]

In [188]:
overall_mean = X.mean(axis=0)

In [189]:
cluster_counts = np.bincount(k.labels_)

In [190]:
inter_variance = 0

for i in range(2):
    inter_variance += cluster_counts[i] * np.sum(
        (centers[i] - overall_mean) ** 2
    )

print("Inter-cluster variance:", inter_variance)

Inter-cluster variance: 678.1912981760938