<a href="https://colab.research.google.com/github/sk-shahsi/ML_Model/blob/master/LDA_Assingment_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns

In [2]:
df = pd.read_csv("/content/pokemon.csv")

In [3]:
df

,name,attack,defense,capture_rate,hp,sp_attack,sp_defense,speed,type
0,Bulbasaur,49,49,45,45,65,65,45,grass
1,Ivysaur,62,63,45,60,80,80,60,grass
2,Venusaur,100,123,45,80,122,120,80,grass
3,Charmander,52,43,45,39,60,50,65,fire
4,Charmeleon,64,58,45,58,80,65,80,fire
...,...,...,...,...,...,...,...,...,...
795,Celesteela,101,103,25,97,107,101,61,steel
796,Kartana,181,131,255,59,59,31,109,grass
797,Guzzlord,101,53,15,223,97,53,43,dark
798,Necrozma,107,101,3,97,127,89,79,psychic
799,Magearna,95,115,3,80,130,115,65,steel

In [7]:
df.dtypes

name            object
attack           int64
defense          int64
capture_rate     int64
hp               int64
sp_attack        int64
sp_defense       int64
speed            int64
type            object
dtype: object