<a href="https://colab.research.google.com/github/sk-shahsi/ML_Model/blob/master/Linear_Regression_Practical.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns


from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error,r2_score

In [ ]:
data=pd.read_csv('/content/Boston.csv')

In [ ]:
data

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

In [ ]:
data.isnull().sum()

crim       0
zn         0
indus      0
chas       0
nox        0
rm         0
age        0
dis        0
rad        0
tax        0
ptratio    0
black      0
lstat      0
medv       0
dtype: int64

In [ ]:
data.duplicated().sum()

np.int64(0)

In [ ]:
data.shape

(506, 14)

In [ ]:
data.dtypes

crim       float64
zn         float64
indus      float64
chas         int64
nox        float64
rm         float64
age        float64
dis        float64
rad          int64
tax          int64
ptratio    float64
black      float64
lstat      float64
medv       float64
dtype: object

In [ ]:
data.drop_duplicates(inplace=True)

In [ ]:
for column in data.select_dtypes(include='number').columns:

    Q1 = data[column].quantile(0.25)
    Q3 = data[column].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - (1.5 * IQR)
    upper = Q3 + (1.5 * IQR)

    outliers = data[(data[column] < lower) | (data[column] > upper)]

    if len(outliers) > 0:
        print(f"{column} has {len(outliers)} outlier(s)")
    else:
        print(f"{column} has no outliers")

crim has 66 outlier(s)
zn has 68 outlier(s)
indus has no outliers
chas has 35 outlier(s)
nox has no outliers
rm has 30 outlier(s)
age has no outliers
dis has 5 outlier(s)
rad has no outliers
tax has no outliers
ptratio has 15 outlier(s)
black has 77 outlier(s)
lstat has 7 outlier(s)
medv has 40 outlier(s)

In [ ]:
#function to check for outliers and remove them from the given columns
def remove_outliers(data, columns):
    for column in columns:
        if column in data.columns:
            Q1 = data[column].quantile(0.25)
            Q3 = data[column].quantile(0.75)
            IQR = Q3 - Q1
            lower_bound = Q1 - 1.5 * IQR
            upper_bound = Q3 + 1.5 * IQR
            data = data[(data[column] >= lower_bound) & (data[column] <= upper_bound)]
    return data

In [ ]:
remove_outliers=remove_outliers(data, data.columns)

In [ ]:
for column in data.select_dtypes(include='number').columns:

    Q1 = data[column].quantile(0.25)
    Q3 = data[column].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - (1.5 * IQR)
    upper = Q3 + (1.5 * IQR)

    outliers = data[(data[column] < lower) | (data[column] > upper)]

    if len(outliers) > 0:
        print(f"{column} has {len(outliers)} outlier(s)")
    else:
        print(f"{column} has no outliers")

crim has 66 outlier(s)
zn has 68 outlier(s)
indus has no outliers
chas has 35 outlier(s)
nox has no outliers
rm has 30 outlier(s)
age has no outliers
dis has 5 outlier(s)
rad has no outliers
tax has no outliers
ptratio has 15 outlier(s)
black has 77 outlier(s)
lstat has 7 outlier(s)
medv has 40 outlier(s)

In [ ]:
data.shape

(506, 14)

In [ ]:
remove_outliers.shape

(214, 14)

In [ ]:
x=data.drop(columns='medv')
y=data['medv']

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2, random_state=100)

In [ ]:
model = LinearRegression()

In [ ]:
model.fit(x_train,y_train)

LinearRegression()

In [ ]:
model.coef_

array([-8.14896492e-02,  4.80407782e-02, -5.47150249e-03,  3.06260576e+00,
       -1.61368815e+01,  3.67245067e+00, -8.51525259e-03, -1.51740854e+00,
        2.87271007e-01, -1.21207598e-02, -9.24160757e-01,  9.53460812e-03,
       -4.85895548e-01])

In [ ]:
model.intercept_ #c value

np.float64(36.33377028550763)

In [ ]:
y_pred=model.predict(x_test)

In [ ]:
pd.DataFrame({'Actual':y_test, 'predicted':y_pred})

     Actual  predicted
198    34.6  34.408110
229    31.5  31.185246
502    20.6  22.312861
31     14.5  17.886139
315    16.2  20.435721
..      ...        ...
166    50.0  36.185086
401     7.2  18.010970
368    50.0  23.182265
140    14.0  13.772710
428    11.0  14.438641

[102 rows x 2 columns]

In [ ]:
r2_score(y_test, y_pred)

0.75550330868713

In [ ]:
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

Mean Squared Error: 23.61699410056368

In [ ]:
rmse = np.sqrt(mse) # mse**0.5
print(rmse)

4.859731895955134

In [ ]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

In [ ]:
vif = pd.DataFrame()
vif['Features'] = x_train.columns
vif['VIF'] = [variance_inflation_factor(x_train.values, i) for i in range(x_train.shape[1])]
vif['VIF'] = round(vif['VIF'], 2)
vif = vif.sort_values(by = "VIF", ascending = False)
vif

   Features    VIF
10  ptratio  89.27
5        rm  79.80
4       nox  74.55
9       tax  60.42
11    black  22.40
6       age  21.60
7       dis  15.34
2     indus  14.99
8       rad  14.69
12    lstat  11.14
1        zn   2.81
0      crim   2.38
3      chas   1.16