<a href="https://colab.research.google.com/github/sk-shahsi/ML_Model/blob/master/Ordanary_Least_Squares.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

OLS -> It is a technique used to find the best fit line(hyperplane) in Linear Regression, by minimizing the sum of squared distances(errors) between the actual and predicted data points
Least Squares -> It minimizes he squared difference between the actual and predicted values
OLS is used to get the coffecient for the relation between Input features and the Target columns
Coffiecient -> m -> Slope, c -> intercept

In [ ]:
# How OLS works ->
# B = [(X.T @ X)^-1] @ X.T @ y
# X.T -> Transpose matrix of X
# ^ -1 -> Inverse
# @ -> Dot product
# X -> Input Feature
# y -> Output Feature
# B -> Coffecient

#    X          y
#    1          2
#    2          3
#    3          5

In [ ]:
# Simple Linear Regression -> One input column and one output column
# y = B0 + B1.X
# intercept (B0)
# Slope (B1)

# X = [1
#      2
#      3]

# To include the intercept(B0), we add a column of ones to X

In [ ]:
# B = [(X.T @ X)^-1] @ X.T @ y

In [ ]:
# Load the data
# Linear Regression
# R2 Score
# MSE

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("/content/Salary_dataset.csv")

In [3]:
df

    Unnamed: 0  YearsExperience    Salary
0            0              1.2   39344.0
1            1              1.4   46206.0
2            2              1.6   37732.0
3            3              2.1   43526.0
4            4              2.3   39892.0
5            5              3.0   56643.0
6            6              3.1   60151.0
7            7              3.3   54446.0
8            8              3.3   64446.0
9            9              3.8   57190.0
10          10              4.0   63219.0
11          11              4.1   55795.0
12          12              4.1   56958.0
13          13              4.2   57082.0
14          14              4.6   61112.0
15          15              5.0   67939.0
16          16              5.2   66030.0
17          17              5.4   83089.0
18          18              6.0   81364.0
19          19              6.1   93941.0
20          20              6.9   91739.0
21          21              7.2   98274.0
22          22              8.0  101303.0
23          23              8.3  113813.0
24          24              8.8  109432.0
25          25              9.1  105583.0
26          26              9.6  116970.0
27          27              9.7  112636.0
28          28             10.4  122392.0
29          29             10.6  121873.0

In [4]:
# Leanear Regression

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       30 non-null     int64
 1   YearsExperience  30 non-null     float64
 2   Salary           30 non-null     float64
dtypes: float64(2), int64(1)
memory usage: 852.0 bytes

In [6]:
x= df["YearsExperience"]
y = df["Salary"]

In [7]:
x.shape

(30,)

In [8]:
y.shape

(30,)

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [24]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)

In [25]:
x_train = pd.DataFrame(x_train)
x_test = pd.DataFrame(x_test)
y_train = pd.DataFrame(y_train)
y_test = pd.DataFrame(y_test)

In [26]:
model = LinearRegression()

In [27]:
model.fit(x_train.values.reshape(-1,1), y_train)

LinearRegression()

In [28]:
y_pred = model.predict(x_test.values.reshape(-1,1))

In [29]:
y_pred

array([[115791.21011287],
       [ 71499.27809463],
       [102597.86866063],
       [ 75268.80422384],
       [ 55478.79204548],
       [ 60190.69970699]])

In [30]:
r2_score(y_test, y_pred)

0.9024461774180497

In [31]:
mean_squared_error(y_test, y_pred)

49830096.855908394

OLS

In [32]:
x=df['YearsExperience'].values
y=df['Salary'].values

In [33]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.1,random_state=42)

In [36]:
x_train = pd.DataFrame(x_train)
x_test = pd.DataFrame(x_test)
y_train = pd.DataFrame(y_train)
y_test = pd.DataFrame(y_test)

In [34]:
import numpy as np

In [37]:
x_train_ols = np.hstack((np.ones((x_train.shape[0], 1)), x_train))
x_test_ols = np.hstack((np.ones((x_test.shape[0], 1)), x_test))

In [39]:
x_train_ols

array([[ 1. ,  5.4],
       [ 1. ,  3.3],
       [ 1. ,  3.8],
       [ 1. , 10.4],
       [ 1. ,  8.8],
       [ 1. ,  4.1],
       [ 1. ,  1.2],
       [ 1. ,  2.3],
       [ 1. ,  5.2],
       [ 1. ,  3. ],
       [ 1. ,  4.2],
       [ 1. ,  4.1],
       [ 1. ,  8. ],
       [ 1. ,  1.4],
       [ 1. ,  1.6],
       [ 1. ,  9.1],
       [ 1. ,  2.1],
       [ 1. ,  7.2],
       [ 1. ,  9.6],
       [ 1. ,  6. ],
       [ 1. , 10.6],
       [ 1. ,  6.9],
       [ 1. ,  3.3],
       [ 1. ,  4. ],
       [ 1. ,  4.6],
       [ 1. ,  6.1],
       [ 1. ,  3.1]])

In [40]:
x_tanspose_ols = x_train_ols.T

In [41]:
beta = np.linalg.inv(x_tanspose_ols @ x_train_ols) @ x_tanspose_ols @ y_train

In [42]:
y_pred_ols = x_test_ols @ beta

In [43]:
y_pred_ols

               0
0  116063.624328
1   72018.452677
2  102943.785964

In [44]:
y_test

          0
0  112636.0
1   67939.0
2  113813.0

In [45]:
r2_score(y_test, y_pred_ols)

0.8928775350863085

In [46]:
mean_squared_error(y_test, y_pred_ols)

48843452.14621681

In [ ]:
# Linear Regression use OLS methods to calculate the cofficent