<a href="https://colab.research.google.com/github/sk-shahsi/ML_Model/blob/master/Time_series.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Data Description**

You have been provided with a data set containing daly sales and profit data of the company for the periode 2011 to 2014. the data set has
the following there attributes.


**Attributes	          Description**

**Order-Date**	     The date on which the order was placed (in dd-mm-yyyy format)

**Sales	Total**      sales value of the transaction (in dollars)

**Profit**	         Profit made on the transaction (in dollars)

***Outline***

In the demonstration, we will:

  .Prepare the data for time series modeling

  .forecasting sales using the following models:

    *Autoregressive(AR)

    *Autoregressive integrated
    moving average(ARIMA)

    *Seasonal autoregressive integrated moving average(SARIMA)

  We will analyze the performance of these models using root of the forcasting models using any one of RMSE or MAPE to obtain a more comprehensive assessment of their performance we will use both measures for each models.

**Part 1-Setup and Dta Preparation**

In this section,we will:

  * Import necessary packages for executing the code
  
  *Load the data

  *Prepare the data for futher analysis

In [1]:
# Import 'numpy ' and pandas for working with numbers and dataframe
import numpy as np
import pandas as pd

#IMport "pyplot" from matplotlib and seaborn from visualization

from matplotlib import pyplot as plt
import seaborn as sns

# Import and execute methods for suppressing warnings

import warnings
from statsmodels.tools.sm_exceptions import ConvergenceWarning
warnings.simplefilter('ignore', ConvergenceWarning)

Let's begin by loading the data and building familiarity with it.

In [3]:
data = pd.read_csv('Superstore_Data.csv')

In [4]:
data

      Order Date      Sales     Profit
0     17-10-2013  5175.1710   919.9710
1     07-11-2011  1822.0800   564.8400
2     14-04-2012  5244.8400   996.4800
3     06-06-2013  3701.5200  1036.0800
4     25-02-2012  1878.7200   582.3600
...          ...        ...        ...
5694  14-01-2013    38.9709   -32.3991
5695  12-11-2014     6.9000    -0.8400
5696  03-11-2011    17.2800   -13.9200
5697  26-07-2013    30.6180     1.0080
5698  19-08-2013     4.5600     0.0000

[5699 rows x 3 columns]

In [6]:
data.head()

   Order Date     Sales    Profit
0  17-10-2013  5175.171   919.971
1  07-11-2011  1822.080   564.840
2  14-04-2012  5244.840   996.480
3  06-06-2013  3701.520  1036.080
4  25-02-2012  1878.720   582.360

In [7]:
data.dtypes

Order Date     object
Sales         float64
Profit        float64
dtype: object

As you can see that data type of the order Date columns is object.but to further conduct analyses on the data,such as grouping by month or year we have to convert the data type of the order date columns to datetime.

In [8]:
data['Order Date'] = pd.to_datetime(data['Order Date'])

/tmp/ipykernel_2809/3021409918.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  data['Order Date'] = pd.to_datetime(data['Order Date'])

In [9]:
data.dtypes

Order Date    datetime64[ns]
Sales                float64
Profit               float64
dtype: object

Let's make sure that the data points in the data frame are ordered by date.